// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package templ

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"seesharpsi/web_roguelike/game"
)

// wallColor is a helper function to map wall types to CSS variable names.
func wallColor(wallType string) string {
	switch wallType {
	case "empty":
		return "var(--wall-empty)"
	case "door":
		return "var(--wall-door)"
	case "hidden_door":
		return "var(--wall-hidden-door)"
	case "indestructible":
		return "var(--wall-indestructible)"
	case "destructible":
		return "var(--wall-destructible)"
	default:
		return "var(--wall-indestructible)" // A fallback for any unknown wall type
	}
}

func MapGrid(m game.Map, p game.Player) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = ThemeVariables("rose-pine").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"map-grid\" style=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues(fmt.Sprintf("grid-template-columns: repeat(%d, 60px); grid-template-rows: repeat(%d, 60px);", m.Width, m.Length))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templ/map.templ`, Line: 32, Col: 122}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for y := m.Length - 1; y >= 0; y-- {
			for x := 0; x < m.Width; x++ {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				current_pos := game.Pos{X: x, Y: y}
				if room, explored := m.Explored[current_pos]; explored {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "  <div class=\"room-cell\" style=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var3 string
					templ_7745c5c3_Var3, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues("border-top-color: " + wallColor(room.NWall.Type) + ";" +
						"border-right-color: " + wallColor(room.EWall.Type) + ";" +
						"border-bottom-color: " + wallColor(room.SWall.Type) + ";" +
						"border-left-color: " + wallColor(room.WWall.Type) + ";")
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `templ/map.templ`, Line: 49, Col: 63}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					hasPlayer := current_pos.X == p.Position.X && current_pos.Y == p.Position.Y
					enemyHealth := 0
					for _, enemy := range m.Enemies {
						if enemy.Position.X == current_pos.X && enemy.Position.Y == current_pos.Y && enemy.Alive {
							enemyHealth = enemy.Health
							break
						}
					}
					if hasPlayer {
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div style=\"width: 20px; height: 20px; background-color: var(--player-color); margin: 20px auto;\"></div>")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					} else if enemyHealth > 0 {
						var templ_7745c5c3_Var4 string
						templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(enemyHealth)
						if templ_7745c5c3_Err != nil {
							return templ.Error{Err: templ_7745c5c3_Err, FileName: `templ/map.templ`, Line: 65, Col: 19}
						}
						_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				} else {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, " <div class=\"empty-cell\"></div>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func Map(m game.Map, p game.Player) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<div class=\"game-map\"><script type=\"text/javascript\" src=\"/static/htmx.min.js\"></script><script>\n\t\tdocument.addEventListener('DOMContentLoaded', function() {\n\t\t\tdocument.addEventListener('keydown', function(event) {\n\t\t\t\tlet direction = null;\n\n\t\t\t\tswitch(event.key) {\n\t\t\t\t\tcase 'ArrowUp':\n\t\t\t\t\t\tdirection = 'north';\n\t\t\t\t\t\tbreak;\n\t\t\t\t\tcase 'ArrowDown':\n\t\t\t\t\t\tdirection = 'south';\n\t\t\t\t\t\tbreak;\n\t\t\t\t\tcase 'ArrowLeft':\n\t\t\t\t\t\tdirection = 'west';\n\t\t\t\t\t\tbreak;\n\t\t\t\t\tcase 'ArrowRight':\n\t\t\t\t\t\tdirection = 'east';\n\t\t\t\t\t\tbreak;\n\t\t\t\t}\n\n\t\t\t\tif (direction) {\n\t\t\t\t\tevent.preventDefault();\n\t\t\t\t\t// Trigger HTMX request\n\t\t\t\t\thtmx.ajax('GET', '/move?direction=' + direction, {\n\t\t\t\t\t\ttarget: '.game-map',\n\t\t\t\t\t\tswap: 'outerHTML'\n\t\t\t\t\t});\n\t\t\t\t}\n\t\t\t});\n\t\t});\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ThemeVariables("rose-pine").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<style>\n\t\t.map-grid {\n\t\t\tdisplay: grid;\n\t\t\tbackground-color: var(--bg-primary);\n            max-width: fit-content;\n            gap: 2px;\n\t\t\t// The grid dimensions are set dynamically via an inline style attribute.\n\t\t}\n\t\t.room-cell, .empty-cell {\n\t\t\twidth: 60px;\n\t\t\theight: 60px;\n\t\t\tbox-sizing: border-box; /* Ensures padding and border are included in the element's total width and height */\n\t\t}\n\t\t.room-cell {\n\t\t\tbackground-color: var(--room-bg);\n\t\t\tborder-style: solid;\n\t\t\tborder-width: 2px; /* A nice, thick border to be visible */\n\t\t\tdisplay: flex;\n\t\t\talign-items: center;\n\t\t\tjustify-content: center;\n\t\t\tfont-weight: bold;\n\t\t\tfont-size: 18px;\n\t\t\tcolor: var(--player-color);\n\t\t}\n\t\t.empty-cell {\n\t\t\tbackground-color: var(--room-unexplored);\n\t\t}\n\t</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = MapGrid(m, p).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<div style=\"margin-top: 20px; text-align: center;\"><div style=\"display: inline-block;\"><div style=\"margin-bottom: 10px;\"><button hx-get=\"/move?direction=north\" hx-target=\".game-map\" hx-swap=\"outerHTML\" style=\"width: 60px; height: 40px; margin: 0 5px;\">↑</button></div><div><button hx-get=\"/move?direction=west\" hx-target=\".game-map\" hx-swap=\"outerHTML\" style=\"width: 60px; height: 40px; margin: 0 5px;\">←</button> <button hx-get=\"/move?direction=east\" hx-target=\".game-map\" hx-swap=\"outerHTML\" style=\"width: 60px; height: 40px; margin: 0 5px;\">→</button></div><div style=\"margin-top: 10px;\"><button hx-get=\"/move?direction=south\" hx-target=\".game-map\" hx-swap=\"outerHTML\" style=\"width: 60px; height: 40px; margin: 0 5px;\">↓</button></div></div></div><div style=\"margin-top: 20px; text-align: center; font-size: 18px; font-weight: bold; color: var(--player-color);\">Health: ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(p.Health)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templ/map.templ`, Line: 179, Col: 18}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</div><div style=\"margin-top: 20px; text-align: center;\"><div style=\"display: inline-block; text-align: left;\"><div style=\"font-weight: bold; margin-bottom: 10px;\">Wall Types:</div><div style=\"display: flex; flex-direction: column; gap: 5px;\"><div style=\"display: flex; align-items: center; gap: 10px;\"><div style=\"width: 20px; height: 20px; border: 2px solid var(--wall-empty); background-color: var(--room-bg);\"></div><span>Empty</span></div><div style=\"display: flex; align-items: center; gap: 10px;\"><div style=\"width: 20px; height: 20px; border: 2px solid var(--wall-door); background-color: var(--room-bg);\"></div><span>Door</span></div><div style=\"display: flex; align-items: center; gap: 10px;\"><div style=\"width: 20px; height: 20px; border: 2px solid var(--wall-hidden-door); background-color: var(--room-bg);\"></div><span>Hidden Door</span></div><div style=\"display: flex; align-items: center; gap: 10px;\"><div style=\"width: 20px; height: 20px; border: 2px solid var(--wall-indestructible); background-color: var(--room-bg);\"></div><span>Indestructible</span></div><div style=\"display: flex; align-items: center; gap: 10px;\"><div style=\"width: 20px; height: 20px; border: 2px solid var(--wall-destructible); background-color: var(--room-bg);\"></div><span>Destructible</span></div></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
