// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package templ

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"seesharpsi/web_roguelike/game"
)

// wallColor is a helper function to map wall types to CSS colors.
func wallColor(wallType string) string {
	switch wallType {
	case "empty":
		return "transparent"
	case "door":
		return "saddlebrown"
	case "hidden_door":
		return "black" // A lighter brown for hidden doors
	case "indestructible":
		return "black"
	case "destructible":
		return "firebrick"
	default:
		return "lightgrey" // A fallback for any unknown wall type
	}
}

func MapGrid(m game.Map, p game.Player) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"map-grid\" style=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues(fmt.Sprintf("grid-template-columns: repeat(%d, 60px); grid-template-rows: repeat(%d, 60px);", m.Width, m.Length))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templ/map.templ`, Line: 31, Col: 122}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for y := m.Length - 1; y >= 0; y-- {
			for x := 0; x < m.Width; x++ {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				current_pos := game.Pos{X: x, Y: y}
				if room, explored := m.Explored[current_pos]; explored {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "  <div class=\"room-cell\" style=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var3 string
					templ_7745c5c3_Var3, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues("border-top-color: " + wallColor(room.NWall.Type) + ";" +
						"border-right-color: " + wallColor(room.EWall.Type) + ";" +
						"border-bottom-color: " + wallColor(room.SWall.Type) + ";" +
						"border-left-color: " + wallColor(room.WWall.Type) + ";")
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `templ/map.templ`, Line: 48, Col: 63}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					if current_pos.X == p.Position.X && current_pos.Y == p.Position.Y {
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "X")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				} else {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, " <div class=\"empty-cell\"></div>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func Map(m game.Map, p game.Player) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<script type=\"text/javascript\" src=\"/static/htmx.min.js\"></script><style>\n\t\t.map-grid {\n\t\t\tdisplay: grid;\n\t\t\t/** border: 2px solid #333; **/\n\t\t\tbackground-color: #f0f0f0;\n            max-width: fit-content;\n            gap: 2px;\n\t\t\t// The grid dimensions are set dynamically via an inline style attribute.\n\t\t}\n\t\t.room-cell, .empty-cell {\n\t\t\twidth: 60px;\n\t\t\theight: 60px;\n\t\t\tbox-sizing: border-box; /* Ensures padding and border are included in the element's total width and height */\n\t\t}\n\t\t.room-cell {\n\t\t\tbackground-color: #fff;\n\t\t\tborder-style: solid;\n\t\t\tborder-width: 2px; /* A nice, thick border to be visible */\n\t\t\tdisplay: flex;\n\t\t\talign-items: center;\n\t\t\tjustify-content: center;\n\t\t\tfont-weight: bold;\n\t\t\tfont-size: 18px;\n\t\t\tcolor: var(--accent-danger, #ea9a97);\n\t\t}\n\t\t.empty-cell {\n\t\t\tbackground-color: #ccc;\n\t\t}\n\t</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = MapGrid(m, p).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<div style=\"margin-top: 20px; text-align: center;\"><div style=\"display: inline-block;\"><div style=\"margin-bottom: 10px;\"><button hx-get=\"/move?direction=north\" hx-target=\".map-grid\" hx-swap=\"outerHTML\" style=\"width: 60px; height: 40px; margin: 0 5px;\">↑</button></div><div><button hx-get=\"/move?direction=west\" hx-target=\".map-grid\" hx-swap=\"outerHTML\" style=\"width: 60px; height: 40px; margin: 0 5px;\">←</button> <button hx-get=\"/move?direction=east\" hx-target=\".map-grid\" hx-swap=\"outerHTML\" style=\"width: 60px; height: 40px; margin: 0 5px;\">→</button></div><div style=\"margin-top: 10px;\"><button hx-get=\"/move?direction=south\" hx-target=\".map-grid\" hx-swap=\"outerHTML\" style=\"width: 60px; height: 40px; margin: 0 5px;\">↓</button></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
