// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package templ

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ThemeVariables(theme string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		switch theme {
		case "nord":
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n\t\t\t:root {\n\t\t\t\t/* Palette - Nord */\n\t\t\t\t--bg-primary: #2E3440;\n\t\t\t\t--bg-secondary: #3B4252;\n\t\t\t\t--bg-tertiary: #434C5E;\n\t\t\t\t--text-primary: #ECEFF4;\n\t\t\t\t--text-secondary: #D8DEE9;\n\t\t\t\t--accent-primary: #88C0D0;\n\t\t\t\t--accent-secondary: #81A1C1;\n\t\t\t\t--accent-danger: #BF616A;\n\t\t\t\t--accent-success: #A3BE8C;\n\t\t\t\t--accent-warning: #EBCB8B;\n\t\t\t\t--border-color: #4C566A;\n\t\t\t\t--wall-empty: transparent;\n\t\t\t\t--wall-door: #8FBCBB;\n\t\t\t\t--wall-indestructible: #2E3440;\n\t\t\t\t--wall-destructible: #BF616A;\n\t\t\t\t--room-bg: #3B4252;\n\t\t\t\t--room-unexplored: #434C5E;\n\t\t\t\t--player-color: #EBCB8B;\n\t\t\t\t--enemy-color: #BF616A;\n\t\t\t}\n\t\t</style>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case "solarized-light":
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<style>\n\t\t\t:root {\n\t\t\t\t/* Palette - Solarized Light */\n\t\t\t\t--bg-primary: #fdf6e3;\n\t\t\t\t--bg-secondary: #eee8d5;\n\t\t\t\t--bg-tertiary: #f5f1e8;\n\t\t\t\t--text-primary: #586e75;\n\t\t\t\t--text-secondary: #839496;\n\t\t\t\t--accent-primary: #268bd2;\n\t\t\t\t--accent-secondary: #2aa198;\n\t\t\t\t--accent-danger: #dc322f;\n\t\t\t\t--accent-success: #859900;\n\t\t\t\t--accent-warning: #b58900;\n\t\t\t\t--border-color: #93a1a1;\n\t\t\t\t--wall-empty: transparent;\n\t\t\t\t--wall-door: #2aa198;\n\t\t\t\t--wall-indestructible: #073642;\n\t\t\t\t--wall-destructible: #dc322f;\n\t\t\t\t--room-bg: #eee8d5;\n\t\t\t\t--room-unexplored: #f5f1e8;\n\t\t\t\t--player-color: #b58900;\n\t\t\t\t--enemy-color: #dc322f;\n\t\t\t}\n\t\t</style>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case "rose-pine", "rosepine":
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<style>\n\t\t\t:root {\n\t\t\t\t/* Palette - Rosé Pine Moon */\n\t\t\t\t--bg-primary: #232136;\n\t\t\t\t--bg-secondary: #2a273f;\n\t\t\t\t--bg-tertiary: #393552;\n\t\t\t\t--text-primary: #e0def4;\n\t\t\t\t--text-secondary: #908caa;\n\t\t\t\t--accent-primary: #c4a7e7;\n\t\t\t\t--accent-secondary: #f6c177;\n\t\t\t\t--accent-danger: #ea9a97;\n\t\t\t\t--accent-success: #9ccfd8;\n\t\t\t\t--accent-warning: #f6c177;\n\t\t\t\t--border-color: #393552;\n\t\t\t\t--wall-empty: transparent;\n\t\t\t\t--wall-door: #9ccfd8;\n\n\t\t\t\t--wall-indestructible: #31748f;\n\t\t\t\t--wall-destructible: #ea9a97;\n\t\t\t\t--room-bg: #2a273f;\n\t\t\t\t--room-unexplored: #393552;\n\t\t\t\t--player-color: #f6c177;\n\t\t\t\t--enemy-color: #ea9a97;\n\t\t\t}\n\t\t</style>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		default:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<style>\n\t\t\t:root {\n\t\t\t\t/* Palette - Rosé Pine Moon (Default) */\n\t\t\t\t--bg-primary: #232136;\n\t\t\t\t--bg-secondary: #2a273f;\n\t\t\t\t--bg-tertiary: #393552;\n\t\t\t\t--text-primary: #e0def4;\n\t\t\t\t--text-secondary: #908caa;\n\t\t\t\t--accent-primary: #c4a7e7;\n\t\t\t\t--accent-secondary: #f6c177;\n\t\t\t\t--accent-danger: #ea9a97;\n\t\t\t\t--accent-success: #9ccfd8;\n\t\t\t\t--accent-warning: #f6c177;\n\t\t\t\t--border-color: #393552;\n\t\t\t\t--wall-empty: transparent;\n\t\t\t\t--wall-door: #9ccfd8;\n\n\t\t\t\t--wall-indestructible: #31748f;\n\t\t\t\t--wall-destructible: #ea9a97;\n\t\t\t\t--room-bg: #2a273f;\n\t\t\t\t--room-unexplored: #393552;\n\t\t\t\t--player-color: #f6c177;\n\t\t\t\t--enemy-color: #ea9a97;\n\t\t\t}\n\t\t</style>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
